//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHotel.SQLHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bill
    {
        public int billID { get; set; }
        public int bookingID { get; set; }
        public int userID { get; set; }
        public int pay { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual tbl_booking tbl_booking { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
