//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHotel.SQLHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_booking()
        {
            this.tbl_bill = new HashSet<tbl_bill>();
            this.note = null;
        }
    
        public int bookingID { get; set; }
        public int userID { get; set; }
        public int roomID { get; set; }
        public System.DateTime checkInDate { get; set; }
        public System.DateTime checkOutDate { get; set; }
        public int odCountPeople { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bill> tbl_bill { get; set; }
        public virtual tbl_room tbl_room { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
